server:
  port: 9010


spring:
    resources:
      #configure static root
      static-locations: classpath:/static/
    datasource:
          driver-class-name: com.mysql.cj.jdbc.Driver
          #database connect params
          url: jdbc:mysql://127.0.0.1:3306/online_food_ordering?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
          username: root
          password:

          initial-size: 1
          min-idle: 1
          max-active: 20
          #get wait time
          max-wait: 60000

          time-between-eviction-runs-millis: 60000

    thymeleaf:
        prefix: classpath:/templates/
        encoding: UTF-8
    mvc:
      view:
       prefix: /
       suffix: .html
      static-path-pattern: /**



## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:Mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.example.Model  # 注意：对应实体类的路径


