server:
  port: 9010


spring:
    datasource:
          driver-class-name: com.mysql.cj.jdbc.Driver
          #基本属性
          url: jdbc:mysql://127.0.0.1:3306/online_food_ordering?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
          username: root
          password:
          #配置初始化大小/最小/最大
          initial-size: 1
          min-idle: 1
          max-active: 20
          #获取连接等待超时时间
          max-wait: 60000
          #间隔多久进行一次检测，检测需要关闭的空闲连接
          time-between-eviction-runs-millis: 60000
          #一个连接在池中最小生存的时间
    thymeleaf:
        prefix: classpath:/templates/
    mvc:
      view:
       prefix: /
       suffix: .html



## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:Mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.example.Model  # 注意：对应实体类的路径


